// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RandomTreasure","status":true,"description":"ランダム宝箱プラグイン","parameters":{"アイテム名格納変数":"13","アイテムアイコン番号格納変数":"12","アイテムのくじの本数格納変数":"11"}}
];
